package com.hlkj.xademo.db132.model;

public class XA132 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_131.id
     *
     * @mbg.generated Thu Mar 31 13:48:19 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_131.name
     *
     * @mbg.generated Thu Mar 31 13:48:19 CST 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_131.id
     *
     * @return the value of xa_131.id
     *
     * @mbg.generated Thu Mar 31 13:48:19 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_131.id
     *
     * @param id the value for xa_131.id
     *
     * @mbg.generated Thu Mar 31 13:48:19 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_131.name
     *
     * @return the value of xa_131.name
     *
     * @mbg.generated Thu Mar 31 13:48:19 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_131.name
     *
     * @param name the value for xa_131.name
     *
     * @mbg.generated Thu Mar 31 13:48:19 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}